spring:
  datasource:
    url: jdbc:postgresql://10.140.0.4:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 10.178.0.10
    username: guest
    password: guest
    port: 5672